version: '3'
services:
  node-express-api:
    build:
      context: ./app-api
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "3000:3000"
    container_name: node-express-api
    volumes:
      - ./app-api:/usr/src/app/app-api
      - /usr/src/app/app-api/node_modules
    env_file:
      - ./app-api/.env.development
    depends_on:
      - database
    links:
      - database
  database:
    image: postgres
    restart: always
    container_name: my_database
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 'user'
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    build:
      context: ./app-db
      dockerfile: Dockerfile.dev
  # angular-ui:
  #   build:
  #     context: ./app-ui
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "5000:5000"
  #   container_name: angular-ui
  #   volumes:
  #      - ./app-ui:/usr/src/app/app-ui
  #      - /usr/src/app/app-ui/node_modules