FROM node:12

RUN mkdir -p /usr/src/app/app-api
WORKDIR /usr/src/app/app-api

COPY package*.json /usr/src/app/app-api/

RUN npm install -g nodemon && npm install

EXPOSE 3000

CMD ["npm", "run", "dev"]