FROM node:12-alpine

WORKDIR /usr/src/app/app-api

COPY package*.json /usr/src/app/app-api/

RUN rm -rf node_modules/
RUN npm install -g sequelize-cli && npm install

COPY . /usr/src/app/app-api/

EXPOSE 3000

CMD npm run dev